



--CREATING DATEID FOR REPORTING WITH TIME SERIES--
--THERE IS SOME DATA CLEANING STEPS--

DROP TABLE IF EXISTS #STAGE_FACT_TRANSACTION_WEB_TRACKING
;

SELECT HHH.PageViewId AS PAGEVIEWID,
       HHH.CookieID AS COOKIEID,
	   HHH.DATEID AS DATEID,
	   HHH.DATEHOURID AS DATEHOURID,
	   HHH.MARKETING_CHANNEL AS MARKETING_CHANNEL,
	   HHH.USER_BROWSER AS USER_BROWSER,
	   CASE WHEN HHH.USER_DEVICE_TYPE = 'UNKNOWN' THEN DEVICE_TYPE_UPDATE.USER_DEVICE_TYPE
	   ELSE HHH.USER_DEVICE_TYPE END AS USER_DEVICE_TYPE,
	   HHH.USER_DEVICE_PROCESSOR
INTO #STAGE_FACT_TRANSACTION_WEB_TRACKING
FROM (
SELECT PageViewId,CookieID,DATEID,DATEHOURID,
USERAGENT AS USER_BROWSER, MARKETING_CHANNEL,
 CASE WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Windows NT%' THEN 'DESKTOP'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Android%' THEN 'MOBILE'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Ýphone%' THEN 'MOBILE'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Ýpad%' THEN 'TABLET'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%X11%' THEN 'TABLET'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Macintosh%' THEN 'DESKTOP'
 WHEN RequestedURL LIKE '%mobile%' THEN 'MOBILE'
 ELSE 'UNKNOWN'
 END AS USER_DEVICE_TYPE,
 DeviceProcessor AS USER_DEVICE_PROCESSOR 
	FROM (
SELECT PageViewId,CookieID,DeviceProcessor,RequestedURL,
	CONVERT(VARCHAR(10), cast(PageViewDateFull as datetime), 112) as DATEID,
CAST(DATEPART(HOUR,   cast(PageViewDateFull as datetime))AS VARCHAR(2)) AS DATEHOURID,
LEFT(UserAgent, CHARINDEX('/', UserAgent + '/') - 1) as 'UserAgent',
    STUFF(UserAgent, 1, CHARINDEX('/', UserAgent + '/'), '') as 'UserAgent_2',
CASE 
       WHEN RefererURL LIKE '%https://www.abcholidays.com%' 
	   OR RefererURL LIKE '%abc.com%'  THEN 'RETAIL'
	   WHEN RefererURL LIKE '%google%' THEN 'GOOGLE'
	   WHEN RefererURL LIKE '%instagram%' THEN 'INSTAGRAM'
	   WHEN RefererURL LIKE '%facebook%' THEN 'FACEBOOK'
	   WHEN RefererURL LIKE '%yahoo%' THEN 'YAHOO'
	   WHEN RefererURL LIKE '%bing%' THEN 'BING'
       WHEN RefererURL LIKE '%duckduckgo%' THEN 'DUCKDUCKGO'
	   WHEN RefererURL LIKE '%presearch%' THEN 'PRESEARCH'
	   WHEN RefererURL LIKE '%ecosia%' THEN 'ECOSIA'
	   WHEN RefererURL LIKE '%findforless%' THEN 'FINDFORLESS'
	   WHEN RefererURL LIKE '%nation%' THEN 'NATION'
	   WHEN RefererURL LIKE '%dnata360%' THEN 'DNATA360'
	   WHEN RefererURL LIKE '%goededeals%' THEN 'GOEDEDEALS'
	   WHEN RefererURL LIKE '%abcvacation%' THEN 'ABCVACATIONS'
	   ELSE 'UNKNOWN' END AS MARKETING_CHANNEL
FROM DBO.STAGE_URL_DATA
WHERE PageViewDateYear = '"'
) HH
UNION ALL 
SELECT PageViewId,CookieID,DATEID,DATEHOURID,
USERAGENT AS USER_BROWSER,MARKETING_CHANNEL,
 CASE WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Windows NT%' THEN 'DESKTOP'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Android%' THEN 'MOBILE'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Ýphone%' THEN 'MOBILE'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Ýpad%' THEN 'TABLET'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%X11%' THEN 'TABLET'
 WHEN  STUFF(UserAgent_2, 1, CHARINDEX('(', UserAgent_2 + '/'), '') 
 LIKE '%Macintosh%' THEN 'DESKTOP'
 WHEN   RequestedURL  LIKE '%mobile%' THEN  'MOBILE'
 ELSE 'UNKNOWN'
 END AS USER_DEVICE_TYPE,
 DeviceProcessor AS USER_DEVICE_PROCESSOR
FROM
(SELECT PageViewId,CookieID,DeviceProcessor,RequestedURL,
(PageViewDateYear*10000 + PageViewDateMonth*100+PageViewDateDay) AS DATEID,
PageViewDateHour as DATEHOURID,
LEFT(UserAgent, CHARINDEX('/', UserAgent + '/') - 1) as 'UserAgent',
    STUFF(UserAgent, 1, CHARINDEX('/', UserAgent + '/'), '') as 'UserAgent_2',
CASE 
       WHEN RefererURL LIKE '%https://www.abcholidays.com%' 
	   OR RefererURL LIKE '%abc.com%'  THEN 'RETAIL'
	   WHEN RefererURL LIKE '%google%' THEN 'GOOGLE'
	   WHEN RefererURL LIKE '%instagram%' THEN 'INSTAGRAM'
	   WHEN RefererURL LIKE '%facebook%' THEN 'FACEBOOK'
	   WHEN RefererURL LIKE '%yahoo%' THEN 'YAHOO'
	   WHEN RefererURL LIKE '%bing%' THEN 'BING'
       WHEN RefererURL LIKE '%duckduckgo%' THEN 'DUCKDUCKGO'
	   WHEN RefererURL LIKE '%presearch%' THEN 'PRESEARCH'
	   WHEN RefererURL LIKE '%ecosia%' THEN 'ECOSIA'
	   WHEN RefererURL LIKE '%findforless%' THEN 'FINDFORLESS'
	   WHEN RefererURL LIKE '%nation%' THEN 'NATION'
	   WHEN RefererURL LIKE '%dnata360%' THEN 'DNATA360'
	   WHEN RefererURL LIKE '%goededeals%' THEN 'GOEDEDEALS'
	   WHEN RefererURL LIKE '%abcvacation%' THEN 'ABCVACATIONS'
	   ELSE 'UNKNOWN' END AS MARKETING_CHANNEL
FROM DBO.STAGE_URL_DATA
WHERE PageViewDateYear <> '"'
) HH 
) HHH
LEFT JOIN (SELECT DISTINCT PageViewId,
CASE 
WHEN TRIM(Device) LIKE '%Xiaomi%' THEN 'MOBILE'
WHEN TRIM(Device) LIKE '%Xiaomi%' THEN 'MOBILE'  
WHEN TRIM(Device) LIKE '%HUAWEI%' THEN 'MOBILE'
WHEN TRIM(Device) LIKE '%OnePlus%' THEN 'MOBILE'
WHEN TRIM(Device) LIKE '%OPPO%' THEN 'MOBILE'
ELSE 'UNKNOWN' END AS USER_DEVICE_TYPE
FROM DBO.STAGE_URL_DATA) DEVICE_TYPE_UPDATE
ON HHH.PageViewId = DEVICE_TYPE_UPDATE.PageViewId
;



DROP TABLE IF EXISTS #TEMP ;
-- create the CTE
WITH cte_split(id, id_2,split_values, csv, iteration) AS
(
	-- anchor member
    SELECT
      PageViewId,
	  CookieID,
      LEFT(REQ_URL, CHARINDEX('/', REQ_URL + '/') - 1),
      STUFF(REQ_URL, 1, CHARINDEX('/', REQ_URL + '/'), ''),
		  0 as iteration
    FROM 
	(select PageViewId,CookieID,replace(RequestedURL,'https://www.abcholidays.com/gb_en/',' ') AS REQ_URL
	FROM dbo.STAGE_URL_DATA) HH 

    UNION ALL

	-- recursive member
    SELECT
      id,
	  id_2,
      LEFT(csv, CHARINDEX('/', csv + '/') - 1),
      STUFF(csv, 1, CHARINDEX('/', csv + '/'), ''),
		  iteration + 1 as 'iteration'
    FROM cte_split
    WHERE
      csv > ''
)
-- use the CTE and generate the final result set
SELECT id AS PAGEVIEW_ID,id_2 as CookieID ,TRIM(UPPER(REPLACE(REPLACE(REPLACE(REPLACE(split_values,'Ç','C'),'Ö','O'),'Ý','I'),'Þ','S'))) AS PARAMETER_TAG_VALUE,
TRIM(UPPER(REPLACE(REPLACE(REPLACE(REPLACE(csv,'Ç','C'),'Ö','O'),'Ý','I'),'Þ','S'))) AS PARAMETER_VALUE,iteration AS PARAMETER_COUNT
INTO #TEMP
FROM cte_split
ORDER BY iteration,id
;

UPDATE #TEMP
SET PARAMETER_VALUE =  NULL 
WHERE PARAMETER_VALUE = ''
;
UPDATE #TEMP
SET PARAMETER_TAG_VALUE =  NULL 
WHERE PARAMETER_TAG_VALUE = ''
;
/*
SELECT PARAMETER_TAG_VALUE,COUNT(1) FROM #TEMP
GROUP BY PARAMETER_TAG_VALUE
ORDER BY  2 DESC
;
SELECT * FROM #TEMP
WHERE PARAMETER_TAG_VALUE = '1C9A69D0-09DC-4CD8-B247-AA811A5D9471'

--HOLIDAYS	23407
--OFFERS	3212
--NULL	3089
--DESTINATION	2853
--?BESTFITDEAL170=1	2007
--HOTELS	1183
--PAGES	364
--DASHBOARD	349

--4415--
SELECT COUNT(DISTINCT CookieID) FROM #TEMP
WHERE PARAMETER_TAG_VALUE  = 'HOTELS'
;
*/


DROP TABLE IF EXISTS #DW_DESTINATION
;
SELECT DISTINCT 
PAGEVIEW_ID,
CookieID, 
CASE WHEN CHARINDEX('?',PARAMETER_VALUE) >0 THEN
LEFT(PARAMETER_VALUE,CHARINDEX('?',PARAMETER_VALUE)-1)
ELSE 
PARAMETER_VALUE
END 
DESTINATION_ALL
INTO #DW_DESTINATION
FROM #TEMP
WHERE PARAMETER_TAG_VALUE = 'DESTINATION'
;



DROP TABLE IF EXISTS #DW_DESTINATION_ALL
;

DECLARE @pattern varchar(52) = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

SELECT DISTINCT PAGEVIEW_ID,CookieID,
  REPLACE(
      TRANSLATE(
         REGION_NAME,
         REPLACE(TRANSLATE(REGION_NAME, @pattern, REPLICATE('a', LEN(@pattern))), 'a', ''),
         REPLICATE('0', LEN(REPLACE(TRANSLATE(REGION_NAME, @pattern, REPLICATE('a', LEN(@pattern))), 'a', '')))
      ),
      '0',
      ''
   ) AS REGION_NAME , 
   REPLACE(
      TRANSLATE(
         REPLACE(REPLACE(COUNTRY_NAME,'#CLOSE',''),'#CHAT',''),
         REPLACE(TRANSLATE(REPLACE(REPLACE(COUNTRY_NAME,'#CLOSE',''),'#CHAT',''), @pattern, REPLICATE('a', LEN(@pattern))), 'a', ''),
         REPLICATE('0', LEN(REPLACE(TRANSLATE(REPLACE(REPLACE(COUNTRY_NAME,'#CLOSE',''),'#CHAT',''), @pattern, REPLICATE('a', LEN(@pattern))), 'a', '')))
      ),
      '0',
      ''
   ) AS COUNTRY_NAME,
    REPLACE(
      TRANSLATE(
         CITY_NAME,
         REPLACE(TRANSLATE(CITY_NAME, @pattern, REPLICATE('a', LEN(@pattern))), 'a', ''),
         REPLICATE('0', LEN(REPLACE(TRANSLATE(CITY_NAME, @pattern, REPLICATE('a', LEN(@pattern))), 'a', '')))
      ),
      '0',
      ''
   ) AS CITY_NAME 
INTO #DW_DESTINATION_ALL
FROM(SELECT DISTINCT  HH.PAGEVIEW_ID,hh.CookieID,HH.REGION_NAME,
    LEFT(HH.COUNTRY_NAME, CHARINDEX('/', HH.COUNTRY_NAME + '/') - 1) as 'COUNTRY_NAME',
    STUFF(HH.COUNTRY_NAME, 1, CHARINDEX('/', HH.COUNTRY_NAME + '/'), '') as 'CITY_NAME'
FROM (
SELECT PAGEVIEW_ID,
        CookieID,
    LEFT(DESTINATION_ALL, CHARINDEX('/', DESTINATION_ALL + '/') - 1) as 'REGION_NAME',
    STUFF(DESTINATION_ALL, 1, CHARINDEX('/', DESTINATION_ALL + '/'), '') as 'COUNTRY_NAME'
FROM #DW_DESTINATION
) HH 
) HHH

UPDATE #DW_DESTINATION_ALL
SET  COUNTRY_NAME =  NULL 
WHERE COUNTRY_NAME = ''
;

UPDATE #DW_DESTINATION_ALL
SET  CITY_NAME =  NULL 
WHERE CITY_NAME = ''
;

DROP TABLE IF EXISTS #DW_REGION 
;
SELECT * 
INTO #DW_REGION
FROM (
SELECT RANK() OVER(ORDER BY HH.REGION_NAME  DESC) DIM_REGION_ID,
       HH.REGION_NAME 
	  
FROM(
SELECT DISTINCT 
REGION_NAME AS  REGION_NAME
FROM #DW_DESTINATION_ALL
WHERE REGION_NAME IS NOT NULL
) HH
UNION ALL 
SELECT DISTINCT '99' AS DIM_REGION_ID,'N/A' AS REGION_NAME
FROM #DW_DESTINATION_ALL
)HHH
;


DROP TABLE IF EXISTS #DW_COUNTRY 
;

SELECT *
INTO #DW_COUNTRY
FROM (
SELECT RANK() OVER(ORDER BY HH.COUNTRY_NAME  DESC) DIM_COUNTRY_ID,
       HH.COUNTRY_NAME 
FROM(
SELECT DISTINCT 
COUNTRY_NAME AS  COUNTRY_NAME
FROM #DW_DESTINATION_ALL
WHERE COUNTRY_NAME IS NOT NULL
) HH
UNION ALL
SELECT DISTINCT '9999' AS DIM_COUNTRY_ID,'N/A' AS COUNTRY_NAME
FROM #DW_DESTINATION_ALL
) HHH
;
/*
SELECT * FROM #DW_COUNTRY
*/

DROP TABLE IF EXISTS #DW_CITY 
;

SELECT * 
INTO #DW_CITY
FROM (
SELECT RANK() OVER(ORDER BY HH.CITY_NAME  DESC) DIM_CITY_ID,
       HH.CITY_NAME
FROM(
SELECT DISTINCT 
CITY_NAME AS  CITY_NAME
FROM #DW_DESTINATION_ALL
WHERE CITY_NAME IS NOT NULL
) HH
UNION ALL
SELECT DISTINCT '9999' AS DIM_CITY_ID,'N/A' AS CITY_NAME
FROM #DW_DESTINATION_ALL
) HHH
;


TRUNCATE TABLE  DBO.DIM_REGION
;
INSERT INTO DBO.DIM_REGION           
SELECT HH.DIM_REGION_REL_ID,
       HH.REGION_NAME,
	   HH.COUNTRY_NAME,
	   HH.CITY_NAME
FROM (
SELECT  DISTINCT  CAST(CONCAT(D_RGN.DIM_REGION_ID,D_CNTRY.DIM_COUNTRY_ID,D_CTY.DIM_CITY_ID) AS INT) AS DIM_REGION_REL_ID,
D_RGN.REGION_NAME,
D_CNTRY.COUNTRY_NAME,
D_CTY.CITY_NAME  
FROM #DW_DESTINATION_ALL DW_D_ALL
LEFT JOIN #DW_REGION D_RGN ON ISNULL(DW_D_ALL.REGION_NAME,'N/A') = D_RGN.REGION_NAME 
LEFT JOIN #DW_COUNTRY D_CNTRY ON ISNULL(DW_D_ALL.COUNTRY_NAME,'N/A') = D_CNTRY.COUNTRY_NAME 
LEFT JOIN #DW_CITY D_CTY ON ISNULL(DW_D_ALL.CITY_NAME,'N/A') = D_CTY.CITY_NAME 
) HH
ORDER BY 1
;


INSERT INTO DBO.DIM_REGION
SELECT DISTINCT '99999999' AS DIM_REGION_REL_ID,'N/A' AS DIM_REGION_NAME,'N/A' AS DIM_COUNTRY_NAME,'N/A' AS DIM_CITY_NAME
FROM #DW_DESTINATION_ALL
;



DROP TABLE IF EXISTS #DW_DEST_TRANSACTION 
;

SELECT PAGEVIEW_ID,CookieID,CAST(CONCAT(D_RGN.DIM_REGION_ID,D_CNTRY.DIM_COUNTRY_ID,D_CTY.DIM_CITY_ID) AS INT) AS DIM_REGION_REL_ID 
INTO #DW_DEST_TRANSACTION
FROM #DW_DESTINATION_ALL DW_DEST_ALL
LEFT JOIN #DW_REGION D_RGN ON ISNULL(DW_DEST_ALL.REGION_NAME,'N/A') = D_RGN.REGION_NAME 
LEFT JOIN #DW_COUNTRY D_CNTRY ON ISNULL(DW_DEST_ALL.COUNTRY_NAME,'N/A') = D_CNTRY.COUNTRY_NAME 
LEFT JOIN #DW_CITY D_CTY ON ISNULL(DW_DEST_ALL.CITY_NAME,'N/A') = D_CTY.CITY_NAME
;


DROP TABLE IF EXISTS #DW_HOLIDAYS_TYPE 
;

SELECT DISTINCT PAGEVIEW_ID,CookieID,
CASE WHEN CHARINDEX('/',PARAMETER_VALUE) >0 THEN
LEFT(PARAMETER_VALUE,CHARINDEX('/',PARAMETER_VALUE)-1)
ELSE 
PARAMETER_VALUE
END 
HOLIDAY_TYPE
INTO #DW_HOLIDAYS_TYPE
FROM  #TEMP
WHERE PARAMETER_TAG_VALUE = 'HOLIDAYS'
;

UPDATE #DW_HOLIDAYS_TYPE
SET HOLIDAY_TYPE =  NULL  
WHERE HOLIDAY_TYPE  LIKE '%[0-9]%'
;

DROP TABLE IF EXISTS #DW_HOLIDAY_TYPE_C 
;

SELECT *
INTO #DW_HOLIDAY_TYPE_C
FROM (
SELECT RANK() OVER(ORDER BY HOLIDAY_TYPE DESC) DIM_HOL_TYPE_ID,
       HH.HOLIDAY_TYPE 
	  
FROM(
SELECT DISTINCT 
 HOLIDAY_TYPE AS HOLIDAY_TYPE
FROM #DW_HOLIDAYS_TYPE
WHERE HOLIDAY_TYPE IS NOT NULL

) HH
UNION ALL 
SELECT '9999' AS DIM_HOL_TYPE_ID,'UNKNOWN' AS HOLIDAY_TYPE
) HHH 
;

TRUNCATE TABLE DBO.DIM_HOLIDAY_TYPE
;
INSERT INTO  dbo.DIM_HOLIDAY_TYPE
SELECT * FROM #DW_HOLIDAY_TYPE_C
;

DROP TABLE IF EXISTS #DW_HOL_TYPE_TRANSACTION 
;

SELECT PAGEVIEW_ID,CookieID,C.DIM_HOL_TYPE_ID
INTO #DW_HOL_TYPE_TRANSACTION
FROM #DW_HOLIDAYS_TYPE DW_DEST_T
LEFT JOIN #DW_HOLIDAY_TYPE_C  C ON ISNULL(DW_DEST_T.HOLIDAY_TYPE,'UNKNOWN') =  C.HOLIDAY_TYPE
;





DROP TABLE IF EXISTS #DW_OFFERS  
;

SELECT HH.PAGEVIEW_ID, HH.CAMPAIGN_NAME,HH.CHANNEL_NAME,HH.OFFER_NAME
INTO #DW_OFFERS
FROM 
(
SELECT DISTINCT PAGEVIEW_ID,
         REPLACE(REPLACE(PARAMETER_VALUE,'?BESTFITDEAL170=1', ''),'#!','')
       AS OFFER_NAME,
	   'RETAIL' AS CHANNEL_NAME,
	   'N/A' AS CAMPAIGN_NAME
FROM #TEMP
WHERE PARAMETER_TAG_VALUE = 'OFFERS'
AND PARAMETER_VALUE NOT LIKE '%SOCIAL_TACTICALAWARENESS%'
AND PARAMETER_VALUE NOT LIKE '%EMAIL%'
AND PARAMETER_VALUE NOT LIKE '%GOOGLE%'
AND PARAMETER_VALUE NOT LIKE '%SOURCE=AMIAI%'
UNION ALL
SELECT DISTINCT PAGEVIEW_ID,
         LEFT(PARAMETER_VALUE, CHARINDEX('?', PARAMETER_VALUE) - 1) AS OFFER_NAME,
		 'EMAIL' AS CHANNEL_NAME,
         REPLACE(REPLACE(SUBSTRING(SUBSTRING(PARAMETER_VALUE, CHARINDEX('&', PARAMETER_VALUE) + 1, LEN(PARAMETER_VALUE)), CHARINDEX('&', SUBSTRING(PARAMETER_VALUE, CHARINDEX('&', PARAMETER_VALUE) + 1, LEN(PARAMETER_VALUE))) + 1, LEN(SUBSTRING(PARAMETER_VALUE, CHARINDEX('&', PARAMETER_VALUE) + 1, LEN(PARAMETER_VALUE)))),'UTM_CAMPAIGN=',''),'&BESTFITDEAL170=1','') CAMPAIGN_NAME
FROM #TEMP
WHERE PARAMETER_TAG_VALUE = 'OFFERS'
AND PARAMETER_VALUE  LIKE '%EMAIL%'
UNION ALL 
SELECT DISTINCT PAGEVIEW_ID,LEFT(PARAMETER_VALUE, CHARINDEX('?', PARAMETER_VALUE) - 1) AS OFFER_NAME,
       'GOOGLE' AS CHANNEL_NAME,
REPLACE(LEFT(SUBSTRING(PARAMETER_VALUE, CHARINDEX('&', PARAMETER_VALUE) + 1, LEN(PARAMETER_VALUE)), CHARINDEX('&', SUBSTRING(PARAMETER_VALUE, CHARINDEX('&', PARAMETER_VALUE) + 1, LEN(PARAMETER_VALUE))) - 1),'KEYWORD=','')	  AS CAMPAIGN_NAME
FROM #TEMP
WHERE PARAMETER_TAG_VALUE = 'OFFERS'
AND PARAMETER_VALUE LIKE '%GOOGLE%'
UNION ALL

SELECT DISTINCT PAGEVIEW_ID,OFFER_NAME,
	   REPLACE(LEFT(SUBSTRING(TAG, CHARINDEX('&', TAG) + 1, LEN(TAG)), CHARINDEX('&', SUBSTRING(TAG, CHARINDEX('&', TAG) + 1, LEN(TAG))) - 1),'UTM_SOURCE=','')     AS CHANNEL_NAME,
	   CAMPAIGN_NAME
FROM (
SELECT PAGEVIEW_ID,OFFER_NAME,
REPLACE(LEFT(TAG, CHARINDEX('&', TAG) - 1),'UTM_CAMPAIGN=','') AS CAMPAIGN_NAME,
SUBSTRING(SUBSTRING(TAG, CHARINDEX('&', TAG) + 1, LEN(TAG)), CHARINDEX('&', SUBSTRING(TAG, CHARINDEX('&', TAG) + 1, LEN(TAG))) + 1, LEN(SUBSTRING(TAG, CHARINDEX('&', TAG) + 1, LEN(TAG))))   AS TAG 
FROM (
SELECT DISTINCT  PAGEVIEW_ID,
LEFT(PARAMETER_VALUE, CHARINDEX('?', PARAMETER_VALUE) - 1) AS OFFER_NAME,
SUBSTRING(SUBSTRING(PARAMETER_VALUE, CHARINDEX('&', PARAMETER_VALUE) + 1, LEN(PARAMETER_VALUE)), CHARINDEX('&', SUBSTRING(PARAMETER_VALUE, CHARINDEX('&', PARAMETER_VALUE) + 1, LEN(PARAMETER_VALUE))) + 1, LEN(SUBSTRING(PARAMETER_VALUE, CHARINDEX('&', PARAMETER_VALUE) + 1, LEN(PARAMETER_VALUE))))
 AS TAG
FROM #TEMP
WHERE PARAMETER_TAG_VALUE = 'OFFERS'
AND PARAMETER_VALUE  LIKE '%SOCIAL_TACTICALAWARENESS%'
) HH 
) HHH
UNION ALL
SELECT DISTINCT  PAGEVIEW_ID,
REPLACE(LEFT(PARAMETER_VALUE, CHARINDEX('?', PARAMETER_VALUE) - 1),'&BESTFITDEAL170=1','')  AS OFFER_NAME,
'AMIAI' AS CHANNEL_NAME,
'N/A' AS CAMPAIGN_NAME
FROM #TEMP
WHERE PARAMETER_TAG_VALUE = 'OFFERS'
AND PARAMETER_VALUE  LIKE '%SOURCE=AMIAI%'
) HH
;

DROP TABLE IF EXISTS #DW_CAMPAIGN 
;

SELECT *
INTO #DW_CAMPAIGN
FROM (
SELECT RANK() OVER(ORDER BY HH.CAMPAIGN_NAME) DIM_CAMPAIGN_ID,
       CAMPAIGN_NAME 
FROM(
SELECT DISTINCT 
 CAMPAIGN_NAME
FROM #DW_OFFERS
WHERE CAMPAIGN_NAME <> 'N/A'
) HH
UNION ALL  
SELECT DISTINCT '9999' AS DIM_CAMPAING_ID,CAMPAIGN_NAME
FROM #DW_OFFERS
WHERE CAMPAIGN_NAME = 'N/A'
UNION ALL 
SELECT '99999' AS DIM_CAMPAING_ID,'CHEAP_RATE_HOTELS' AS CAMPAIGN_NAME
) HH
;


TRUNCATE TABLE DBO.DIM_CAMPAIGN
;


INSERT INTO DBO.DIM_CAMPAIGN
SELECT * FROM #DW_CAMPAIGN
;

DROP TABLE IF EXISTS #DW_CHANNEL 
;
SELECT *
 INTO #DW_CHANNEL
FROM (
SELECT RANK() OVER(ORDER BY HH.CHANNEL_NAME  DESC) DIM_CHANNEL_ID,
       CHANNEL_NAME 
	  
FROM(
SELECT DISTINCT 
 CHANNEL_NAME
FROM #DW_OFFERS
) HH
UNION ALL
SELECT DISTINCT '9999' AS DIM_CHANNEL_ID ,'N/A' AS CHANNEL_NAME
FROM  #DW_OFFERS
) HHH
;


DROP TABLE IF EXISTS #DW_OFFER_DESC 
;
SELECT * 
 INTO #DW_OFFER_DESC
FROM (
SELECT RANK() OVER(ORDER BY HH.OFFER_NAME DESC) DIM_OFFER_DESC_ID,
       OFFER_NAME 
	  
FROM(
SELECT DISTINCT 
 OFFER_NAME
FROM #DW_OFFERS
) HH
UNION ALL 
SELECT DISTINCT '9999' AS DIM_OFFER_DESC_ID,'N/A' AS OFFER_NAME
FROM #DW_OFFERS
) HH
;
 

DROP TABLE IF EXISTS #DW_OFFER_TRANSACTION
;
SELECT DISTINCT DW_OF.PAGEVIEW_ID,
       DIM_CAMPAIGN_ID,
	   DIM_OFFER_DESC_ID,
	   DIM_CHANNEL_ID,
	   DW_OF.CAMPAIGN_NAME,
	   DW_OF.OFFER_NAME,
	   DW_OF.CHANNEL_NAME
INTO #DW_OFFER_TRANSACTION
FROM #DW_OFFERS DW_OF
LEFT JOIN #DW_CAMPAIGN D_CAMP ON ISNULL(DW_OF.CAMPAIGN_NAME,'N/A') =  D_CAMP.CAMPAIGN_NAME
LEFT JOIN #DW_CHANNEL D_CHAN ON ISNULL(DW_OF.CHANNEL_NAME,'N/A') =  D_CHAN.CHANNEL_NAME
LEFT JOIN #DW_OFFER_DESC  D_OFFR_DESC ON ISNULL(DW_OF.OFFER_NAME,'N/A') =  D_OFFR_DESC.OFFER_NAME
;

TRUNCATE TABLE  [dbo].[DIM_OFFER];

INSERT INTO [dbo].[DIM_OFFER]
SELECT DISTINCT DIM_OFFER_DESC_ID,OFFER_NAME
FROM #DW_OFFER_TRANSACTION
UNION ALL
SELECT '9999' AS DIM_OFFER_DESC_ID,'N/A' AS OFFER_NAME
;



DROP TABLE IF EXISTS #DW_HOTEL_TRANSACTION
;

SELECT HOTEL_ALL.* 
INTO #DW_HOTEL_TRANSACTION
FROM (
SELECT DISTINCT    PAGEVIEW_ID,
        REPLACE(STUFF(LEFT(STUFF(HOTEL_COUNTRY_3, 1, CHARINDEX('/', HOTEL_COUNTRY_3 + '/'), ''), CHARINDEX('?', STUFF(HOTEL_COUNTRY_3, 1, CHARINDEX('/', HOTEL_COUNTRY_3 + '/'), '')+ '?') - 1), 1, CHARINDEX('/', LEFT(STUFF(HOTEL_COUNTRY_3, 1, CHARINDEX('/', HOTEL_COUNTRY_3 + '/'), ''), CHARINDEX('?', STUFF(HOTEL_COUNTRY_3, 1, CHARINDEX('/', HOTEL_COUNTRY_3 + '/'), '')+ '?') - 1) + '/'), ''),'.HTML','') AS HOTEL_NAME	,
CASE WHEN  HOTEL_COUNTRY =  HOTEL_COUNTRY_2 THEN HOTEL_COUNTRY
	  ELSE HOTEL_COUNTRY END AS HOTEL_COUNTRY,
	   LEFT(STUFF(HOTEL_COUNTRY_3, 1, CHARINDEX('/', HOTEL_COUNTRY_3 + '/'), '') , CHARINDEX('/', STUFF(HOTEL_COUNTRY_3, 1, CHARINDEX('/', HOTEL_COUNTRY_3 + '/'), '') + '/') - 1) 
	   AS HOTEL_CITY,
      CAST(NULL AS date) AS HOTEL_CHEAP_START_DATE,
	  CAST(NULL AS date) AS HOTEL_CHEAP_END_DATE,
	  '0' AS HOTEL_CHEAP_FLAG	   
FROM (
SELECT DISTINCT PAGEVIEW_ID,
LEFT(PARAMETER_VALUE, CHARINDEX('/', PARAMETER_VALUE+ '/') - 1) as 'HOTEL_COUNTRY',
LEFT(STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), ''), CHARINDEX('/', STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '')+ '/') - 1) AS HOTEL_COUNTRY_2,
    STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '') as 'HOTEL_COUNTRY_3'
FROM #TEMP 
WHERE PAGEVIEW_ID NOT IN 
(SELECT HH.PAGEVIEW_ID 
FROM (
SELECT DISTINCT PAGEVIEW_ID   FROM  #DW_HOL_TYPE_TRANSACTION --HOLIDAYS
UNION ALL
SELECT DISTINCT PAGEVIEW_ID FROM #DW_OFFER_TRANSACTION --OFFERS
UNION ALL 
SELECT DISTINCT PAGEVIEW_ID FROM #DW_DEST_TRANSACTION  --DESTINATION
) HH
)
AND PARAMETER_TAG_VALUE  = 'HOTELS'
AND PARAMETER_VALUE IS NOT NULL
AND PARAMETER_VALUE NOT LIKE '%CHEAP_RATES%'
) HHH
WHERE HOTEL_COUNTRY NOT LIKE'%[^a-zA-Z0-9 ]%'
AND HOTEL_COUNTRY != 'BOOK' 
UNION ALL
SELECT DISTINCT PAGEVIEW_ID,
	   REPLACE(REPLACE(CASE WHEN HOTEL_NAME_1 LIKE '%ATLANTIS_HOTEL%' THEN 'ATLANTIS_HOTEL'
	        ELSE HOTEL_NAME_1 END,'HOTEL_HOTEL','HOTEL'),'.HTML?FID=154&TM=1','') AS HOTEL_NAME,
	   HOTEL_COUNTRY,
	   HOTEL_CITY,
	   CAST(NULL AS date) AS HOTEL_CHEAP_START_DATE,
	   CAST(NULL AS date) AS HOTEL_CHEAP_END_DATE,
	   '0' AS HOTEL_CHEAP_FLAG
FROM (
SELECT DISTINCT PAGEVIEW_ID,
       HOTEL_COUNTRY,
	   CASE WHEN HOTEL_COUNTRY_2 LIKE '%DUBAI%' THEN 'DUBAI'
	        WHEN HOTEL_COUNTRY_2 LIKE '%PHUKET%' THEN 'PHUKET'
			WHEN HOTEL_COUNTRY_2 LIKE '%BALI%' THEN 'BALI'
			WHEN HOTEL_COUNTRY_2 LIKE '%CHIANG%' THEN 'CHIANG'
			WHEN HOTEL_COUNTRY_2 LIKE '%SINGAPORE%' THEN 'SIGNAPORE'
			WHEN HOTEL_COUNTRY_2 LIKE '%PORT_LUIS%' THEN 'PORT_LUIS'
			WHEN HOTEL_COUNTRY_2 LIKE '%FRANKFURT%' THEN 'FRANKFURT'
			WHEN HOTEL_COUNTRY_2 LIKE '%ABU_DHABI%' THEN 'ABU_DHABI'
			WHEN HOTEL_COUNTRY_2  LIKE '%ABERDEEN%' THEN 'ABERDEEN'
			WHEN HOTEL_COUNTRY_2 LIKE '%TROU_DEAU_DOUCE%' THEN 'TROU_DEAU_DOUCE'
			WHEN HOTEL_COUNTRY_2 LIKE '%BELLE_MARE%' THEN 'BELLE_MARE'
			WHEN HOTEL_COUNTRY_2 LIKE '%KUALA_LUMPUR%'THEN  'KUALA_LUMPUR'
			WHEN HOTEL_COUNTRY_2 LIKE '%PANGKOK%' THEN 'PANGKOK'
			WHEN HOTEL_COUNTRY_2 LIKE '%BEL_OMBRE%' THEN 'BEL_OMBRE'
			WHEN HOTEL_COUNTRY_2 LIKE '%MAHBOURG%' THEN 'MAHBOURG'
			WHEN HOTEL_COUNTRY_2 LIKE '%LANGKAWI%' THEN 'LANGKAWI'
			WHEN HOTEL_COUNTRY_2 LIKE '%PENANG%' THEN 'PENANG'
			WHEN HOTEL_COUNTRY_2 LIKE '%FUJAIRAH%' THEN 'FUJAIRAH'
			ELSE HOTEL_COUNTRY_2 END AS HOTEL_CITY,
			--_BANG_TAO/BANYAN_TREE_PHUKET_HOTEL.HTML?TM=1&BESTFITDEAL170=1
			REPLACE(REPLACE(REPLACE(REPLACE(STUFF(HOTEL_COUNTRY_3, 1, CHARINDEX('/', HOTEL_COUNTRY_3 + '/'), ''),'CHEAP_RATES_',''),'_BANG_TAO/',''),'&BESTFITDEAL170=1',''),'.HTML?TM=1','') AS HOTEL_NAME_1
FROM (
SELECT DISTINCT PAGEVIEW_ID,
LEFT(PARAMETER_VALUE, CHARINDEX('/', PARAMETER_VALUE+ '/') - 1) as 'HOTEL_COUNTRY',
LEFT(STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), ''), CHARINDEX('/', STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '')+ '/') - 1) AS HOTEL_COUNTRY_2,
    STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '') as 'HOTEL_COUNTRY_3'
FROM #TEMP 
WHERE PAGEVIEW_ID NOT IN 
(SELECT HH.PAGEVIEW_ID 
FROM (
SELECT DISTINCT PAGEVIEW_ID   FROM  #DW_HOL_TYPE_TRANSACTION --HOLIDAYS
UNION ALL
SELECT DISTINCT PAGEVIEW_ID FROM #DW_OFFER_TRANSACTION --OFFERS
UNION ALL 
SELECT DISTINCT PAGEVIEW_ID FROM #DW_DEST_TRANSACTION  --DESTINATION
) HH
)
AND PARAMETER_TAG_VALUE  = 'HOTELS'
AND PARAMETER_VALUE IS NOT NULL
AND PARAMETER_VALUE  LIKE '%CHEAP_RATES%'
AND PARAMETER_VALUE NOT LIKE '%STARTDATE%'
) HHH
) HHHH
UNION ALL
SELECT DISTINCT PAGEVIEW_ID,
     HOTEL_NAME,
     HOTEL_COUNTRY,
	 HOTEL_CITY,
	 CONVERT(VARCHAR(10), cast(HOTEL_START_DATE as datetime), 112) AS HOTEL_CHEAP_START_DATE,
     CONVERT(VARCHAR(10), cast(REPLACE(LEFT(HOTEL_CHAR_2, CHARINDEX('&', HOTEL_CHAR_2+ '&') - 1),'ENDDATE=','') as datetime), 112)	  AS HOTEL_CHEAP_END_DATE,
	 '1' AS HOTEL_CHEAP_FLAG
FROM (
SELECT DISTINCT PAGEVIEW_ID,
       HOTEL_COUNTRY,
	   HOTEL_CITY,
	   LEFT(HOTEL_NAME_1, CHARINDEX('&', HOTEL_NAME_1+ '&') - 1) AS HOTEL_NAME,
       REPLACE(LEFT(STUFF(STUFF(HOTEL_NAME_1, 1, CHARINDEX('&', HOTEL_NAME_1 + '&'), ''), 1, CHARINDEX('&', STUFF(HOTEL_NAME_1, 1, CHARINDEX('&', HOTEL_NAME_1 + '&'), '') + '&'), '') , CHARINDEX('&', STUFF(STUFF(HOTEL_NAME_1, 1, CHARINDEX('&', HOTEL_NAME_1 + '&'), ''), 1, CHARINDEX('&', STUFF(HOTEL_NAME_1, 1, CHARINDEX('&', HOTEL_NAME_1 + '&'), '') + '&'), '') + '&') - 1),'STARTDATE=','')	    AS HOTEL_START_DATE,
      STUFF(STUFF(STUFF(HOTEL_NAME_1, 1, CHARINDEX('&', HOTEL_NAME_1 + '&'), ''), 1, CHARINDEX('&', STUFF(HOTEL_NAME_1, 1, CHARINDEX('&', HOTEL_NAME_1 + '&'), '') + '&'), '') , 1, CHARINDEX('&', STUFF(STUFF(HOTEL_NAME_1, 1, CHARINDEX('&', HOTEL_NAME_1 + '&'), ''), 1, CHARINDEX('&', STUFF(HOTEL_NAME_1, 1, CHARINDEX('&', HOTEL_NAME_1 + '&'), '') + '&'), '')  + '&'), '') AS HOTEL_CHAR_2
FROM (
SELECT DISTINCT PAGEVIEW_ID,
       HOTEL_COUNTRY,
	   CASE WHEN HOTEL_COUNTRY_2 LIKE '%DUBAI%' THEN 'DUBAI'
	        WHEN HOTEL_COUNTRY_2 LIKE '%PHUKET%' THEN 'PHUKET'
			WHEN HOTEL_COUNTRY_2 LIKE '%BALI%' THEN 'BALI'
			WHEN HOTEL_COUNTRY_2 LIKE '%CHIANG%' THEN 'CHIANG'
			WHEN HOTEL_COUNTRY_2 LIKE '%SINGAPORE%' THEN 'SIGNAPORE'
			WHEN HOTEL_COUNTRY_2 LIKE '%PORT_LUIS%' THEN 'PORT_LUIS'
			WHEN HOTEL_COUNTRY_2 LIKE '%FRANKFURT%' THEN 'FRANKFURT'
			WHEN HOTEL_COUNTRY_2 LIKE '%ABU_DHABI%' THEN 'ABU_DHABI'
			WHEN HOTEL_COUNTRY_2  LIKE '%ABERDEEN%' THEN 'ABERDEEN'
			WHEN HOTEL_COUNTRY_2 LIKE '%TROU_DEAU_DOUCE%' THEN 'TROU_DEAU_DOUCE'
			WHEN HOTEL_COUNTRY_2 LIKE '%BELLE_MARE%' THEN 'BELLE_MARE'
			WHEN HOTEL_COUNTRY_2 LIKE '%KUALA_LUMPUR%'THEN  'KUALA_LUMPUR'
			WHEN HOTEL_COUNTRY_2 LIKE '%PANGKOK%' THEN 'PANGKOK'
			WHEN HOTEL_COUNTRY_2 LIKE '%BEL_OMBRE%' THEN 'BEL_OMBRE'
			WHEN HOTEL_COUNTRY_2 LIKE '%MAHBOURG%' THEN 'MAHBOURG'
			WHEN HOTEL_COUNTRY_2 LIKE '%LANGKAWI%' THEN 'LANGKAWI'
			WHEN HOTEL_COUNTRY_2 LIKE '%PENANG%' THEN 'PENANG'
			WHEN HOTEL_COUNTRY_2 LIKE '%FUJAIRAH%' THEN 'FUJAIRAH'
			ELSE HOTEL_COUNTRY_2 END AS HOTEL_CITY,
			--_BANG_TAO/BANYAN_TREE_PHUKET_HOTEL.HTML?TM=1&BESTFITDEAL170=1
			REPLACE(REPLACE(REPLACE(REPLACE(STUFF(HOTEL_COUNTRY_3, 1, CHARINDEX('/', HOTEL_COUNTRY_3 + '/'), ''),'CHEAP_RATES_',''),'_BANG_TAO/',''),'&BESTFITDEAL170=1',''),'.HTML?TM=1','') AS HOTEL_NAME_1
FROM (
SELECT DISTINCT PAGEVIEW_ID,
LEFT(PARAMETER_VALUE, CHARINDEX('/', PARAMETER_VALUE+ '/') - 1) as 'HOTEL_COUNTRY',
LEFT(STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), ''), CHARINDEX('/', STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '')+ '/') - 1) AS HOTEL_COUNTRY_2,
    STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '') as 'HOTEL_COUNTRY_3'
FROM #TEMP 
WHERE PAGEVIEW_ID NOT IN 
(SELECT HH.PAGEVIEW_ID 
FROM (
SELECT DISTINCT PAGEVIEW_ID   FROM  #DW_HOL_TYPE_TRANSACTION --HOLIDAYS
UNION ALL
SELECT DISTINCT PAGEVIEW_ID FROM #DW_OFFER_TRANSACTION --OFFERS
UNION ALL 
SELECT DISTINCT PAGEVIEW_ID FROM #DW_DEST_TRANSACTION  --DESTINATION
) HH
)
AND PARAMETER_TAG_VALUE  = 'HOTELS'
AND PARAMETER_VALUE IS NOT NULL
AND PARAMETER_VALUE  LIKE '%CHEAP_RATES%'
AND PARAMETER_VALUE  LIKE '%STARTDATE%'
) HHH
) HHHH
) HHHHH
) HOTEL_ALL
;

INSERT INTO  #DW_HOTEL_TRANSACTION
SELECT HH.PAGEVIEW_ID,
       HH.HOTEL_NAME,
	   HH.HOTEL_COUNTRY,
	   HH.HOTEL_CITY,
	   CAST(NULL AS DATE) HOTEL_CHEAP_START_DATE,
	   CAST(NULL AS DATE) HOTEL_CHEAP_END_DATE,
	   '0'  AS HOTEL_CHEAP_FLAG

FROM (
SELECT DISTINCT PAGEVIEW_ID,
LEFT(PARAMETER_VALUE, CHARINDEX('/', PARAMETER_VALUE+ '/') - 1) AS HOTEL_COUNTRY,
LEFT(STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), ''), CHARINDEX('/', STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '')+ '/') - 1) AS HOTEL_CITY,
REPLACE(LEFT(STUFF(STUFF(STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), ''), 1, CHARINDEX('/', STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '') + '/'), '') , 1, CHARINDEX('/', STUFF(STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), ''), 1, CHARINDEX('/', STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '') + '/'), '')  + '/'), '')  , CHARINDEX('?', STUFF(STUFF(STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), ''), 1, CHARINDEX('/', STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '') + '/'), '') , 1, CHARINDEX('/', STUFF(STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), ''), 1, CHARINDEX('/', STUFF(PARAMETER_VALUE, 1, CHARINDEX('/', PARAMETER_VALUE + '/'), '') + '/'), '')  + '/'), '')  + '?') - 1)  
  ,'.HTML','') AS HOTEL_NAME
FROM #TEMP 
WHERE PAGEVIEW_ID NOT IN 
(SELECT HH.PAGEVIEW_ID 
FROM (
SELECT DISTINCT PAGEVIEW_ID   FROM  #DW_HOL_TYPE_TRANSACTION --HOLIDAYS
UNION ALL
SELECT DISTINCT PAGEVIEW_ID FROM #DW_OFFER_TRANSACTION --OFFERS
UNION ALL 
SELECT DISTINCT PAGEVIEW_ID FROM #DW_DEST_TRANSACTION  --DESTINATION
) HH
)
AND PARAMETER_TAG_VALUE  = 'HOTELS'
AND PARAMETER_VALUE IS NOT NULL
AND PARAMETER_VALUE NOT LIKE '%CHEAP_RATES%'
AND PAGEVIEW_ID NOT IN (SELECT PAGEVIEW_ID FROM #DW_HOTEL_TRANSACTION)
) HH 
WHERE HOTEL_NAME LIKE '%[a-zA-Z]%'
AND HOTEL_COUNTRY != 'BOOK' 
;







/*
SELECT DISTINCT PAGEVIEW_ID,
                PARAMETER_TAG_VALUE AS HOTEL_COUNTRY,
				REPLACE(PARAMETER_VALUE,'?BESTFITDEAL170=1','') AS HOTEL_NAME

FROM #TEMP 
WHERE PAGEVIEW_ID NOT IN 
(SELECT HH.PAGEVIEW_ID 
FROM (
SELECT DISTINCT PAGEVIEW_ID   FROM  #DW_HOL_TYPE_TRANSACTION --HOLIDAYS
UNION ALL
SELECT DISTINCT PAGEVIEW_ID FROM #DW_OFFER_TRANSACTION --OFFERS
UNION ALL 
SELECT DISTINCT PAGEVIEW_ID FROM #DW_DEST_TRANSACTION  --DESTINATION
UNION ALL 
SELECT DISTINCT PAGEVIEW_ID FROM #DW_HOTEL_TRANSACTION
) HH
)
AND PARAMETER_TAG_VALUE NOT IN ('CONTACT-US','PAGES','DASHBOARD','?BESTFITDEAL170=1')
AND PARAMETER_TAG_VALUE LIKE '%[a-zA-Z]%'
AND PARAMETER_TAG_VALUE NOT LIKE '%BESTFITDEAL170=1%'
AND PARAMETER_VALUE IS NOT NULL 
AND PARAMETER_VALUE  LIKE '%[a-zA-Z]%'
AND PARAMETER_TAG_VALUE IN ('SEYCHELLES','MALDIVES')
*/

--TRANSACTION CONTROLS--
SELECT *
INTO #TRANSACTION_ALL
FROM (
SELECT DISTINCT  ISNULL(HHH.PAGEVIEW_ID,KK.PAGEVIEW_ID) AS PAGEVIEW_ID, 
ISNULL(HHH.PARAMETER_TAG_VALUE,KK.PARAMETER_TAG_VALUE) AS PARAMETER_TAG_VALUE
FROM (
SELECT PAGEVIEW_ID,PARAMETER_TAG_VALUE
FROM #TEMP
WHERE PARAMETER_TAG_VALUE IN ('HOTELS','OFFERS','DESTINATION','TOUR','FLIGHTS','OPTIONS','HOLIDAYS')
) KK
LEFT JOIN (SELECT HH.PAGEVIEW_ID,'HOLIDAYS' AS PARAMETER_TAG_VALUE
FROM (
SELECT PAGEVIEW_ID,COUNT(DISTINCT PARAMETER_TAG_VALUE) SAY
FROM #TEMP
WHERE PARAMETER_TAG_VALUE IN ('HOTELS','OFFERS','DESTINATION','TOUR','FLIGHTS','OPTIONS','HOLIDAYS')
GROUP BY PAGEVIEW_ID
HAVING COUNT(DISTINCT PARAMETER_TAG_VALUE) >1
)HH
) HHH ON KK.PAGEVIEW_ID =  HHH.PAGEVIEW_ID

UNION ALL
SELECT PAGEVIEW_ID,'BOOKING' AS PARAMETER_TAG_VALUE
FROM #TEMP
WHERE PARAMETER_TAG_VALUE NOT IN ('HOTELS','OFFERS','DESTINATION','TOUR','FLIGHTS','OPTIONS')
AND PARAMETER_TAG_VALUE LIKE '%BOOK%' 
AND PAGEVIEW_ID NOT IN (SELECT HH.PAGEVIEW_ID
FROM (
SELECT PAGEVIEW_ID,COUNT(DISTINCT PARAMETER_TAG_VALUE) SAY
FROM #TEMP
WHERE PARAMETER_TAG_VALUE IN ('HOTELS','OFFERS','DESTINATION','TOUR','FLIGHTS','OPTIONS','HOLIDAYS')
GROUP BY PAGEVIEW_ID
HAVING COUNT(DISTINCT PARAMETER_TAG_VALUE) >1
)HH)
UNION ALL 
SELECT PAGEVIEW_ID,'HOLIDAYS' AS PARAMETER_TAG_VALUE
FROM #TEMP
WHERE PARAMETER_TAG_VALUE NOT IN ('HOTELS','OFFERS','DESTINATION','TOUR','FLIGHTS','OPTIONS')
AND PARAMETER_TAG_VALUE NOT LIKE '%BOOK%'
AND PARAMETER_VALUE LIKE '%HOLIDAYS%'
--AND PAGEVIEW_ID = '3529197847'
UNION ALL 
SELECT PAGEVIEW_ID,'TOURS' AS PARAMETER_TAG_VALUE
FROM #TEMP
WHERE PARAMETER_TAG_VALUE NOT IN ('HOTELS','OFFERS','DESTINATION','TOUR','FLIGHTS','OPTIONS')
AND PARAMETER_TAG_VALUE NOT LIKE '%BOOK%'
AND PARAMETER_VALUE LIKE '%TOURS%'
) HHA 
;

UPDATE #TRANSACTION_ALL
SET PARAMETER_TAG_VALUE = 'HOLIDAYS'
WHERE PAGEVIEW_ID IN (
SELECT PAGEVIEW_ID
FROM(
SELECT PAGEVIEW_ID,COUNT(1) SAY FROM #TRANSACTION_ALL
GROUP BY PAGEVIEW_ID
HAVING COUNT(1)>1
) A
) 

DROP TABLE IF EXISTS #DW_TRANSACTION_SOURCE 
;

SELECT DISTINCT *
INTO #DW_TRANSACTION_SOURCE
FROM #TRANSACTION_ALL


SELECT * FROM #TRANSACTION_ALL

ALTER TABLE DBO.FACT_WEB_TRACTING
ALTER COLUMN DIM_REGION_REL_ID NVARCHAR(MAX)
;

ALTER TABLE DBO.FACT_WEB_TRACTING
ADD TRANS_SOURCE NVARCHAR(MAX) NULL

truncate table [dbo].[FACT_WEB_TRACTING]
;

insert into [dbo].[FACT_WEB_TRACTING]
SELECT WEB.PAGEVIEWID,
       WEB.COOKIEID,
	   WEB.DATEID,
	   WEB.DATEHOURID,
	   WEB.MARKETING_CHANNEL,
	   WEB.USER_BROWSER,
	   WEB.USER_DEVICE_TYPE,
	   WEB.USER_DEVICE_PROCESSOR,
	  CASE WHEN DEST_TRANS.DIM_REGION_REL_ID IS NULL THEN '99999999'
	  ELSE DEST_TRANS.DIM_REGION_REL_ID END  DIM_REGION_REL_ID,
	   ISNULL(HOL_TRANS.DIM_HOL_TYPE_ID,'9999') DIM_HOL_TYPE_ID,
	   CASE WHEN HOTEL_TRANS.HOTEL_CHEAP_FLAG = '1' THEN 'CHEAP_RATES'
	   ELSE ISNULL(OFFER_TRANS.CAMPAIGN_NAME,'N/A') END CAMPAIGN_NAME,
	   OFFER_TRANS.CHANNEL_NAME,
	   ISNULL(OFFER_TRANS.DIM_OFFER_DESC_ID,'9999') AS DIM_OFFER_ID,
	   ISNULL(OFFER_TRANS.OFFER_NAME,'N/A') OFFER_NAME,
	   CASE WHEN HOTEL_TRANS.HOTEL_CHEAP_FLAG = '1' THEN '99999'
	   ELSE ISNULL(OFFER_TRANS.DIM_CAMPAIGN_ID,'9999') 
	   END DIM_CAMPAIGN_ID,
	   OFFER_TRANS.DIM_CHANNEL_ID,
	   HOTEL_TRANS.HOTEL_NAME,
	   HOTEL_TRANS.HOTEL_COUNTRY,
	   HOTEL_TRANS.HOTEL_CITY,
	   HOTEL_TRANS.HOTEL_CHEAP_FLAG,
	   HOTEL_TRANS.HOTEL_CHEAP_START_DATE,
	   HOTEL_TRANS.HOTEL_CHEAP_START_DATE,
	   ISNULL(TRANSACTION_ALL.PARAMETER_TAG_VALUE,'OTHER')
	   AS TRANS_SOURCE 
FROM #STAGE_FACT_TRANSACTION_WEB_TRACKING WEB
LEFT JOIN #DW_DEST_TRANSACTION DEST_TRANS ON WEB.PAGEVIEWID =  DEST_TRANS.PAGEVIEW_ID
LEFT JOIN #DW_HOL_TYPE_TRANSACTION HOL_TRANS ON WEB.PAGEVIEWID =  HOL_TRANS.PAGEVIEW_ID
LEFT JOIN #DW_OFFER_TRANSACTION OFFER_TRANS ON WEB.PAGEVIEWID =  OFFER_TRANS.PAGEVIEW_ID
LEFT JOIN #DW_HOTEL_TRANSACTION HOTEL_TRANS ON WEB.PAGEVIEWID =  HOTEL_TRANS.PAGEVIEW_ID
LEFT JOIN #DW_TRANSACTION_SOURCE TRANSACTION_ALL  ON WEB.PAGEVIEWID =  TRANSACTION_ALL.PAGEVIEW_ID
;


DROP TABLE IF EXISTS #DW_SALES_TYPE 
;

SELECT COOKIEID,SALES_TYPE 
INTO #DW_SALES_TYPE
FROM 
(
SELECT DISTINCT COOKIEID,TRANS_SOURCE AS  SALES_TYPE FROM DBO.FACT_WEB_TRACTING
WHERE COOKIEID IN (
SELECT COOKIEID 
FROM (
SELECT COOKIEID,COUNT(DISTINCT TRANS_SOURCE) SAY
FROM DBO.FACT_WEB_TRACTING
GROUP BY COOKIEID
HAVING COUNT(DISTINCT TRANS_SOURCE) = 1
) HH 
) 
UNION ALL
SELECT DISTINCT COOKIEID,'HOLIDAYS' AS  SALES_TYPE FROM DBO.FACT_WEB_TRACTING
WHERE COOKIEID IN (
SELECT COOKIEID 
FROM (
SELECT COOKIEID,COUNT(DISTINCT TRANS_SOURCE) SAY
FROM DBO.FACT_WEB_TRACTING
GROUP BY COOKIEID
HAVING COUNT(DISTINCT TRANS_SOURCE) > 1
) HH 
) 
) HHHH
;

UPDATE DBO.FACT_WEB_TRACTING 
SET SALES_TYPE = D.SALES_TYPE
FROM DBO.FACT_WEB_TRACTING F
INNER JOIN #DW_SALES_TYPE D 
ON F.COOKIEID =  D.COOKIEID
;

SELECT COOKIEID,COUNT(DISTINCT SALES_TYPE) FROM DBO.FACT_WEB_TRACTING
GROUP BY COOKIEID
HAVING COUNT(DISTINCT SALES_TYPE) >1
;

UPDATE DBO.FACT_WEB_TRACTING
SET TRANS_SOURCE = 'DESTINATION'
WHERE TRANS_SOURCE  ='DESTINAT'
;

UPDATE DBO.FACT_WEB_TRACTING
SET SALES_TYPE = 'DESTINATION'
WHERE SALES_TYPE  ='DESTINAT'
;

 ;
TRUNCATE TABLE DBO.DIM_HOUR;


INSERT INTO DBO.DIM_HOUR
SELECT * 
FROM (
SELECT DISTINCT 0 AS DIM_HOUR_ID, '00:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 1 AS DIM_HOUR_ID, '01:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 2 AS DIM_HOUR_ID, '02:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 3 AS DIM_HOUR_ID, '03:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 4 AS DIM_HOUR_ID, '04:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 5 AS DIM_HOUR_ID, '05:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 6 AS DIM_HOUR_ID, '06:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 7 AS DIM_HOUR_ID, '07:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 8 AS DIM_HOUR_ID, '08:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 9 AS DIM_HOUR_ID, '09:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 10 AS DIM_HOUR_ID, '10:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 11 AS DIM_HOUR_ID, '11:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 12 AS DIM_HOUR_ID, '12:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 13 AS DIM_HOUR_ID, '13:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 14 AS DIM_HOUR_ID, '14:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL
SELECT DISTINCT 15 AS DIM_HOUR_ID, '15:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 16 AS DIM_HOUR_ID, '16:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 17 AS DIM_HOUR_ID, '17:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 18 AS DIM_HOUR_ID, '18:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 19 AS DIM_HOUR_ID, '19:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 20 AS DIM_HOUR_ID, '20:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 21 AS DIM_HOUR_ID, '21:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 22 AS DIM_HOUR_ID, '22:00' AS DIM_HOUR
FROM DIM_DATE
UNION ALL 
SELECT DISTINCT 23 AS DIM_HOUR_ID, '23:00' AS DIM_HOUR
FROM DIM_DATE
) HH
;







 WITH 
        cte_n1 (n) AS (SELECT 1 FROM (VALUES (1),(1),(1),(1),(1),(1),(1),(1),(1),(1)) n (n)),   -- 10
        cte_n2 (n) AS (SELECT 1 FROM cte_n1 a CROSS JOIN cte_n1 b),                             -- 100
        cte_Calendar (dt) AS (
            SELECT TOP (DATEDIFF(DAY, '2012-01-01', '2030-12-31') + 1)
                CONVERT(DATE, DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) - 1, '2012-01-01'))
            FROM
                cte_n2 a CROSS JOIN cte_n2 b                                                    -- 10,000
            )
    SELECT
        ID = DATEDIFF(DAY, '2012-01-01', c.dt) + 1,
        [Year] = YEAR(c.dt),
        [Month] = MONTH(c.dt),
        [Day] = DAY(c.dt)
    FROM
        cte_Calendar c





